blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogDetailView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("blog/new", BlogCreateView.as_view(), name="blog_create"),
    path("blog/edit/<int:pk>", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/detail/<int:pk>", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/delete/<int:pk>", BlogDeleteView.as_view(), name="blog_delete"),
]

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("main.urls", "mailing"), namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

from main.utils import NULLABLE
from users.models import User


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержание")
    image = models.ImageField(
        upload_to="blog_images/", **NULLABLE, verbose_name="Изображение"
    )
    views = models.PositiveIntegerField(default=0)
    publish_date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
    )

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ["-publish_date"]
        permissions = [
            ("can_create_blogpost", "can create blogpost"),
            ("can_update_blogpost", "can update blogpost"),
            ("can_delete_blogpost", "can delete blogpost"),
        ]

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from blog.models import Blog


class StyleFormMixin:

    def add_bootstrap_classes(self):
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.TextInput):
                field.widget.attrs.update({"class": "form-control"})
            elif isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({"class": "form-control"})
            elif isinstance(field.widget, forms.FileInput):
                field.widget.attrs.update({"class": "form-control-file"})
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs.update({"class": "form-control"})
            elif isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs.update({"class": "form-check-input"})
            elif isinstance(field.widget, forms.RadioSelect):
                field.widget.attrs.update({"class": "form-check-input"})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_bootstrap_classes()


FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "content", "image"]

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if any(word in title.lower() for word in FORBIDDEN_WORDS):
            raise ValidationError("Заголовок содержит запрещённые слова.")
        return title

    def clean_content(self):
        content = self.cleaned_data.get("content")
        if content and any(word in content.lower() for word in FORBIDDEN_WORDS):
            raise ValidationError("Содержимое статьи содержит запрещённые слова.")
        return content

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DeleteView,
    UpdateView,
    CreateView,
    DetailView,
)
from django.core.cache import cache

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import get_blogs_from_cache


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog
    extra_context = {"title": "Сообщения"}

    def get_queryset(self):
        """Получаем блоги из кэша, если кэш пуст, получаем данные из БД."""
        return get_blogs_from_cache()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["can_create_blogpost"] = self.request.user.has_perm(
            "blog.can_create_blogpost"
        )
        context["can_update_blogpost"] = self.request.user.has_perm(
            "blog.can_update_blogpost"
        )
        context["can_delete_blogpost"] = self.request.user.has_perm(
            "blog.can_delete_blogpost"
        )
        return context


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    permission_required = "blog.can_create_blogpost"
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        cache.clear()
        form.instance.user = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = "blog.can_update_blogpost"
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        cache.clear()
        return super().form_valid(form)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = "blog.can_delete_blogpost"
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        cache.clear()
        return super().form_valid(form)

blog/templates/blog/blog_confirm_delete.html
{% extends "main/base.html" %}

{% load static %}
{% load form_tags %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm bg-light">
                    <div class="card-header bg-primary text-white text-center ">
                        <h2>Удаление статьи</h2>
                    </div>
                    <div class="card-body py-3 rounded-pill">
                        <h5 class="mb-3 text-center">Хотите удалить статью: {{ object.title }}?</h5>
                    </div>
                    <div class="card-footer d-flex justify-content-between py-2">
                        <form method="post" enctype="multipart/form-data" class="w-100 d-flex justify-content-between">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger flex-grow-1 me-2 rounded-pill">Удалить</button>
                            <a class="btn btn-outline-primary flex-grow-1 ms-2 rounded-pill" href="{% url 'blog:blog_list' %}" role="button">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col-4">
                    <div class="card shadow-sm">

                        {% if blogpost.image %}
                            <img src="{{ blogpost.image | media_filter }}" alt=""
                                 style="width: 400px; height: 400px; object-fit: cover;">
                        {% else %}
                            <img src="{% static 'media_default/blog_img.png' %}" alt=""
                                 style="width: 400px; height: 400px; object-fit: cover;">
                        {% endif %}
                        <div class="card-body">
                            <p class="card-text">Название: {{ object.title | truncatechars:45 }}</p>
                            <p class="card-text">Содержание: {{ object.content | truncatechars:150 }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-outline-secondary" href="{% url 'blog:blog_list' %}"
                                       role="button">Назад</a>
                                </div>
                                <small class="text-body-secondary"
                                       style="color: gray;"> {{ object.publish_date }}</small>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card col-8">
                    <p class="btn text-primary border-light flex">Контент:</p>
                    <p class="card-body"> {{ object.content }}</p>
                </div>
                <div class="col-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Описание</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">Заголовок</th>
                            <td>{{ object.title }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Автор</th>
                            <td>{{ object.user }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Дата создания</th>
                            <td>{{ object.publish_date }}</td>

                        </tr>
                        <tr>
                            <th scope="row" class="text-primary border-light">Количество просмотров</th>
                            <td class="text-primary border-light">{{ object.views }}</td>

                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow-sm bg-light" style="border-radius: 30px;">
                <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                    {% if object %}
                        <h2>Редактирование статьи</h2>
                    {% else %}
                        <h2>Создание статьи</h2>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success rounded-pill" type="submit">Сохранить</button>
                        <a class="btn btn-secondary rounded-pill" href="{% url 'blog:blog_list' %}"
                           role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "main/base.html" %}
{% load my_tags %}
{% load static %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="col-12">

                <div class="row">
                    <!-- Кнопка "Добавить" -->
                    {% if can_create_blogpost %}
                        <div class="col-1 d-flex justify-content-start">
                            <a class="btn btn-outline-primary btn-circle-add d-flex justify-content-center align-items-center mx-auto"
                               href="{% url 'blog:blog_create' %}"
                               role="button">
                                <img src="{% static 'crud_icons/add.png' %}" alt="Добавить новую версию"
                                     class="btn-add-icon">
                            </a>
                        </div>
                    {% endif %}
                    <div class="col-7 d-flex justify-content-start">
                        <h6 class="text-danger">Только контент-менеджер может добавлять или изменять статьи!<br>
                            <small class="text-primary">Либо пользователь должен быть superuser.</small>
                        </h6>
                    </div>
                </div>

            </div>

            <!-- Список блогов -->
            <div class="row">

                {% for blogpost in object_list %}
                    <div class="col-6 mb-4">
                        <div class="card h-100 d-flex flex-row" style="margin-bottom: 0;">
                            <!-- Левый блок с изображением и кнопками -->
                            <div class="d-flex flex-column align-items-center card-img-left" style="flex-shrink: 0;">
                                {% if blogpost.image %}
                                    <img class="ms-lg-2 mt-2" src="{{ blogpost.image | media_filter }}" alt=""
                                         style="width: 200px; height: 200px; object-fit: cover;">
                                {% else %}
                                    <img class="ms-lg-2 mt-2" src="{% static 'media_default/blog_img.png' %}" alt=""
                                         style="width: 200px; height: 200px; object-fit: cover;">
                                {% endif %}

                                <!-- Блок с кнопками под изображением -->
                                <div class="btn-group text-center mt-3">
                                    <a class="btn btn-outline-secondary btn-circle"
                                       href="{% url 'blog:blog_detail' blogpost.pk %}"
                                       role="button" title="Инфо">
                                        <img src="{% static 'crud_icons/info.png' %}" alt="Инфо"
                                             class="btn-icon">
                                    </a>
                                    {% if user.is_superuser or can_update_blogpost %}
                                        <a class="btn btn-outline-secondary btn-circle"
                                           href="{% url 'blog:blog_update' blogpost.pk %}"
                                           role="button" title="Изменить">
                                            <img src="{% static 'crud_icons/edit.png' %}" alt="Изменить"
                                                 class="btn-icon">
                                        </a>
                                    {% endif %}
                                    {% if user.is_superuser or can_delete_blogpost %}
                                        <a class="btn btn-outline-secondary btn-circle btn-delete"
                                           href="{% url 'blog:blog_delete' blogpost.pk %}"
                                           role="button" title="Удалить">
                                            <img src="{% static 'crud_icons/delete.png' %}" alt="Удалить"
                                                 class="btn-icon">
                                        </a>
                                    {% endif %}
                                </div>
                            </div>

                            <!-- Правый блок с информацией о статье -->
                            <div class="card-body">
                                <div class="card-header">
                                    <h5>{{ blogpost.title | truncatechars:30}}</h5>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                        {{ blogpost.content | truncatechars:49 }}
                                    </li>
                                    <li class="list-group-item">
                                        Автор: {{ blogpost.user }}
                                    </li>
                                    <li class="list-group-item">
                                        Дата публикации: {{ blogpost.publish_date }}
                                    </li>
                                    <li class="list-group-item">
                                        <div class="text-primary fw-bold">
                                            Количество просмотров: {{ blogpost.views }}
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}