blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogDetailView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("blog/new", BlogCreateView.as_view(), name="blog_create"),
    path("blog/edit/<int:pk>", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/detail/<int:pk>", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/delete/<int:pk>", BlogDeleteView.as_view(), name="blog_delete"),
]

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("main.urls", "mailing"), namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    email_verification,
    PasswordResetView,
    UserListView,
    UserUpdateView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("email-confirm/<str:token>/", email_verification, name="email_verification"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    path("users/", UserListView.as_view(), name="user_list"),
    path("user/edit/<int:pk>", UserUpdateView.as_view(), name="user_update"),
]

main/models.py
from django.db import models
from main.utils import NULLABLE
from users.models import User


class Client(models.Model):
    email = models.EmailField(verbose_name="Почта", unique=True)
    first_name = models.CharField(max_length=200, **NULLABLE, verbose_name="Имя")
    last_name = models.CharField(max_length=200, **NULLABLE, verbose_name="Фамилия")
    comment = models.TextField(**NULLABLE, verbose_name="Комментарий")
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ("email",)
        permissions = [
            ("can_view_clients", "can view clients"),
            ("can_change_clients", "can change clients"),
            ("can_delete_clients", "can delete clients"),
        ]

    def __str__(self):
        return f"{self.email}"


class Message(models.Model):
    subject = models.CharField(max_length=200, verbose_name="Тема")
    body = models.TextField(verbose_name="Содержание")
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        **NULLABLE,
        related_name="Owner",
        verbose_name="Пользователь",
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ("subject",)
        permissions = [
            ("can_change_message", "can change message"),
            ("can_delete_message", "can delete message"),
        ]

    def __str__(self):
        return f"{self.subject}"


class Mailing(models.Model):
    clients = models.ManyToManyField(
        Client,
        related_name="mailings",
        verbose_name="Клиент с почтой",
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.SET_NULL,
        **NULLABLE,
        related_name="mailings",
        verbose_name="massage",
    )
    send_date = models.DateTimeField(**NULLABLE, verbose_name="Дата начала рассылки")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания рассылки"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения рассылки"
    )
    is_active = models.BooleanField(default=True)

    COMPLETED = "completed"
    CREATED = "created"
    STARTED = "started"
    DAY = "once a day"
    MINUTE = "once a minute"
    WEEK = "once a week"
    MONTH = "once a month"
    STATUS = [(COMPLETED, "completed"), (CREATED, "created"), (STARTED, "started")]
    INTERVAL = [
        (MINUTE, "once a minute"),
        (DAY, "once a days"),
        (WEEK, "once a week"),
        (MONTH, "once a months"),
    ]

    interval = models.CharField(choices=INTERVAL, default=WEEK, verbose_name="Интервал")
    status = models.CharField(choices=STATUS, default=CREATED, verbose_name="Статус")
    end_date = models.DateTimeField(**NULLABLE, verbose_name="Дата окончания рассылки")
    auto_start = models.BooleanField(default=True, verbose_name="Автоматический старт")

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Пользователь"
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ("interval",)
        permissions = [
            ("can_change_mailing", "can change mailing"),
            ("can_delete_mailing", "can delete mailing"),
            ("can_view_mailing", "can view mailing"),
            ("can_create_mailing", "can create mailing"),
            ("can_switch_mailing", "can switch mailing"),
        ]

        def __str__(self):
            return f"Рассылка {self.pk}"


class TryMailing(models.Model):
    SUCCESS = "success"
    FAILURE = "failure"
    STATUSES = [(SUCCESS, "success"), (FAILURE, "failure")]
    last_try = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата последней попытки"
    )
    status = models.CharField(choices=STATUSES, default=SUCCESS, verbose_name="Статус")
    response = models.TextField(**NULLABLE, verbose_name="Ответ")
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        related_name="logs",
        verbose_name="Рассылка",
    )

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"
        ordering = ("status",)

    def __str__(self):
        return f"{self.status}"

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

from main.utils import NULLABLE


class User(AbstractUser):
    username = None
    phone = models.CharField(max_length=35, verbose_name="Телефон", **NULLABLE)
    avatar = models.ImageField(upload_to="users/", verbose_name="Аватар", **NULLABLE)
    email = models.EmailField(unique=True, verbose_name="Почта")
    country = models.CharField(max_length=50, verbose_name="Страна", **NULLABLE)
    token = models.CharField(
        max_length=100, verbose_name="Токен авторизации", **NULLABLE
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Юзер"
        verbose_name_plural = "Юзеры"
        ordering = ("email",)
        permissions = [
            ("can_view_users_list", "can view users list"),
            ("can_block_user", "can block user"),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import HiddenInput, ModelForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "first_name", "last_name", "phone", "avatar", "country"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = HiddenInput()


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["is_active"]

users/views.py
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserProfileForm, UserForm
from users.models import User

from mailing.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        user.token = token
        user.save()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение регистрации",
            message=f"Добро пожаловать на сайт! Для подтверждения регистрации перейди по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class PasswordResetView(View):
    form_class = PasswordResetForm
    template_name = "users/password_reset.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            try:
                user = User.objects.get(email=email)
                new_password = User.objects.make_random_password()
                user.password = make_password(new_password)
                user.save()

                send_mail(
                    subject="Восстановление пароля",
                    message=f"Ваш новый пароль: {new_password}",
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[email],
                )
                return redirect(reverse("users:login"))
            except User.DoesNotExist:
                form.add_error("email", "Пользователь с таким email не найден")
        return render(request, self.template_name, {"form": form})


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile.html"
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    permission_required = "users.can_view_users_list"


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    permission_required = "users.can_block_user"
    success_url = reverse_lazy("users:user_list")

users/templates/users/login.html
{% extends "main/base.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm " style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                        <h2>Вход</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">Войти</button>
                            <a class="btn btn-outline-secondary" href="{% url 'main:client_list' %}"
                               role="button">Назад</a>
                        </form>
                    </div>
                    <div class="card-footer bg-primary text-center"
                         style="border-bottom-left-radius: 30px; border-bottom-right-radius: 30px;">
                        <a class="text-white" href="{% url 'users:register' %}">Нет аккаунта? Зарегистрируйтесь</a><br>
                        <a class="text-white" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm bg-light" style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                            <h2>Восстановление пароля</h2>
                    </div>
                    <div class="card-body py-3 flex-grow-1 ms-2">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary rounded-pill">
                                    Восстановить
                            </button>
                            <a class="btn btn-outline-secondary rounded-pill" href="{% url 'users:login' %}"
                               role="button">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends "main/base.html" %}
{% load my_tags %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                    <h2>Аватар</h2>
                </div>
                <div class="card shadow-sm " style="border-radius: 30px;">
                    {% if object.avatar %}
                        <img src="{{ object.avatar | media_filter }}" alt="avatar">
                    {% else %}
                        <img src="{% static 'media_default/default_avatar.png' %}" alt="default_avatar">
                    {% endif %}
                </div>
                <div class="card-footer bg-primary text-white text-center" style="border-bottom-left-radius: 30px; border-bottom-right-radius: 30px;" >
                    <p class="card-text" >{{ object.last_name }} {{ object.first_name }} | Тел.: {{ object.phone }}</p>
                </div>
            </div>
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm " style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                        <h2>Профиль</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">Сохранить</button>
                            <a class="btn btn-outline-secondary" href="{% url 'main:client_list' %}"
                               role="button">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
 {% extends "main/base.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm " style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                        <h2>Регистрация</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">Зарегистрироваться</button>
                            <a class="btn btn-outline-secondary" href="{% url 'main:client_list' %}"
                               role="button">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow-sm bg-light" style="border-radius: 30px;">
                <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                    {% if object %}
                        <h2>Редактирование информации пользователя</h2>
                    {% else %}
                        <h2>Создание пользователя</h2>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success rounded-pill" type="submit">Сохранить</button>
                        <a class="btn btn-secondary rounded-pill" href="{% url 'users:user_list' %}"
                           role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                {% for user in object_list %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-header">
                                <h5><small>Активность: </small>{{ user.is_active }}</h5>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    Email: {{ user.email }}
                                </li>
                                <li class="list-group-item">
                                    Телефон: {{ user.phone }}
                                </li>
                                <li class="list-group-item">
                                    <div class="btn-group text-center">
                                        <a class="btn btn-outline-secondary btn-circle"
                                           href="{% url 'users:user_update' user.pk %}"
                                           role="button" title="Изменить">
                                            <img src="{% static 'crud_icons/edit.png' %}" alt="Изменить"
                                                 class="btn-icon">
                                        </a>
                                        <a class="btn btn-outline-secondary btn-circle btn-delete"
                                           href="{% url 'main:client_delete' user.pk %}"
                                           role="button" title="Удалить">
                                            <img src="{% static 'crud_icons/delete.png' %}" alt="Удалить"
                                                 class="btn-icon">
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}